// App.tsx — AppShell version with FusionShell layout. Generated by scaffold-appshell.
import { HashRouter, Routes, Route, Outlet, Navigate } from 'react-router-dom'
import ErrorBoundary from './ErrorBoundary'
import { FusionProvider } from './contexts/fusion'
import FusionShell from './components/FusionShell'
import { FUSION_CONFIG } from './navigation'
import OnboardingPage from './pages/OnboardingPage'
import WorkspacePage from './pages/WorkspacePage'
import HomePage from './pages/HomePage'

function AppLayout() {
  return (
    <FusionShell businessName={FUSION_CONFIG.businessName}>
      <Outlet />
    </FusionShell>
  )
}

export default function App() {
  return (
    <ErrorBoundary>
      <HashRouter>
        <FusionProvider pathPrefix={FUSION_CONFIG.pathPrefix || ''}>
          <Routes>
            <Route path="/onboarding" element={<OnboardingPage />} />
            <Route element={<AppLayout />}>
              <Route path="/" element={<Navigate to="/home" replace />} />
              <Route path="/home" element={<HomePage />} />
              <Route path="/workspace" element={<WorkspacePage />} />
              <Route path="*" element={<WorkspacePage />} />
            </Route>
          </Routes>
        </FusionProvider>
      </HashRouter>
    </ErrorBoundary>
  )
}
